config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, controllers:{
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

 # namespace :users do
  scope module: :users do
    root to: 'homes#top'
    get 'home/about' => 'homes#about'

    get '/search' => 'search#search'

    get '/users/check' => "users#check", as: 'users_check'
    patch '/users/hide' => "users#hide", as: 'users_hide'

    resources :users, only: [:index, :show, :edit, :update, ] do
      resource :relationships, onry: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
    end

    resources :chat_rooms, only: [:create, :index, :show, :destroy] do
      resources :chats, only: [:create, :destroy]
    end
    get 'sort' => 'chat_rooms#sort'

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
    post 'contacts/back', to: 'contacts#back', as: 'back'
    get 'done', to: 'contacts#done', as: 'done'

    resources :blogs, only: [:index, :show] do
      resources :blog_comments, only: [:index, :create, :destroy]
    end

  end

  namespace :admins do

    resources :blogs do
      resources :blog_comments, only: [:destroy]
    end

    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end

    resources :chat_rooms, only: [:index, :show, :destroy] do
      resources :chats, only: [:destroy]
    end

    resources :contacts, only: [:index, :show]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/blog.rb
class Blog < ApplicationRecord

  has_one_attached :blog_image

  has_many :blog_comments, dependent: :destroy

  # 評価の平均
  def avg_score
    unless self.blog_comments.empty?
      blog_comments.average(:evaluation).round(1).to_f
    else
      0.0
    end
  end

  # 評価の％
  def review_score_percentage
    unless self.blog_comments.empty?
      blog_comments.average(:evaluation).round(1).to_f*100/5
    else
      0.0
    end
  end

  # validates :blog_image, attached_file_presence: true
  # ↑別パターンのバリデーション（今回は使わない）
  validates :blog_image, presence: true, blob: { content_type: :image }
  validates :title, presence: true
  validates :text, presence: true

end

app/controllers/admins/blogs_controller.rb
class Admins::BlogsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save!
      redirect_to admins_blog_path(@blog)
    else
      render "new_admins_blog_path"
    end
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    redirect_to admins_blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to admins_blogs_path
  end

  private

    def blog_params
      params.require(:blog).permit(:title, :text, :blog_image)
    end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admins_user_path(@user)
  end

  protected

  def user_params
    params.require(:user).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :user_image, :user_name, :text, :is_deleted )
  end

end

app/controllers/users/blog_comments_controller.rb
class Users::BlogCommentsController < ApplicationController

  before_action :authenticate_user!

  def index
    @blog = Blog.find(params[:blog_id])
    @blog_comments = @blog.blog_comments
  end

  def create
    @blog = Blog.find(params[:blog_id])
    blog_comment = BlogComment.new(blog_comment_params)
    blog_comment.user_id = current_user.id
    blog_comment.blog_id = @blog.id
    if blog_comment.save
      redirect_to blog_path(@blog)
    else
      redirect_to blog_path(@blog)
    end
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    blog_comment = @blog.blog_comments.find(params[:id])
    if blog_comment.user_id != current_user.id
      redirect_to blog_path(@blog)
    else
      blog_comment.destroy
      redirect_to blog_path(@blog)
    end
  end

  private

  def blog_comment_params
    params.require(:blog_comment).permit(:comment, :evaluation)
  end

end

app/controllers/users/blogs_controller.rb
class Users::BlogsController < ApplicationController

  def index
    @blogs = Blog.page(params[:page]).per(5).reverse_order
  end

  def show
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
  end

end

app/controllers/users/chat_rooms_controller.rb
class Users::ChatRoomsController < ApplicationController

  before_action :authenticate_user!

  def index
    @chat_rooms = ChatRoom.page(params[:page]).per(10).reverse_order
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
    @chat = Chat.new
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    @chat_room.user_id = current_user.id
    if @chat_room.save!
      redirect_to chat_room_path(@chat_room)
    else
      @chat_rooms = ChatRoom.all
      render :index
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])
    if @chat_room.user_id != current_user.id
      redirect_to chat_rooms_path
    else
      @chat_room.destroy
      redirect_to chat_rooms_path
    end
  end

  private

    def chat_room_params
      params.require(:chat_room).permit(:room_name)
    end

    def sort_params
      params.permit(:sort)
    end

end

app/controllers/users/chats_controller.rb
class Users::ChatsController < ApplicationController

  before_action :authenticate_user!

  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    chat = Chat.new(chat_params)
    chat.chat_room_id = @chat_room.id
    chat.user_id = current_user.id
    if chat.save!
      redirect_to chat_room_path(@chat_room)
    else
      render 'chat_rooms/show'
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:chat_room_id])
    chat = @chat_room.chats.find(params[:id])
    if chat.user_id != current_user.id
      redirect_to chat_room_path(@chat_room.id)
    else
      chat.destroy
      redirect_to chat_room_path(@chat_room.id)
    end
  end

  def chat_params
    params.require(:chat).permit(:response)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController

  # 入力画面
  def new
    @contact = Contact.new
  end

  # 入力確認
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  # 入力ミスなどで戻るときに入力データを保持した状態で戻る
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 入力データ保存
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_path
    else
      render :new
    end
  end

  # 完了画面
  def done
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:email,:name,:title,:message)
  end

end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController

  def top
  end

  def about
  end



end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save
    #redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
    #redirect_back(fallback_location: root_path)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/post_comments_controller.rb
class Users::PostCommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    post_comment = PostComment.new(post_comment_params)
    post_comment.user_id = current_user.id
    post_comment.post_id = @post.id
    if post_comment.save
      redirect_to post_path(@post)
    else
      @user = @book.user
      render 'error'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    if @post.user_id != current_user.id
      redirect_to post_path(@post)
    end
    post_comment = @post.post_comments.find(params[:id])
    post_comment.destroy
    redirect_to post_path(@post)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController

  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save!
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @user = current_user
    @posts = Post.page(params[:page]).per(5).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to posts_path
    end
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to posts_path
    else
      @post.destroy
      redirect_to user_path(@post.user)
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :text, :post_image)
    end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController

  before_action :authenticate_user!

# フォロー機能を作成・保存・削除
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

# フォロー・フォロワー一覧を表示
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController

  def search
    # ↓選択したmodelを@modelに代入
    @model = params["search"]["model"]
    # ↓検索にかけた文字列を@valueに代入
    @value = params["search"]["value"]
    # ↓選択した検索方法howを@howに代入
    @how = params["search"]["how"]
    # ↓search_forの引数にインスタンス変数を定義、最終的な検索結果が入る
    @datas = search_for(@how, @model, @value)
    
    @user = current_user
    
  end
  
  
  private
  # ↓def search_forでhowがmatchだった場合の処理
  def match(model, value)
    # ↓modelがuserの場合の処理
    if model == 'user'
      # ↓whereでvalueと完全一致するuser_nameを探す
      User.where(user_name: value)
    elsif model == 'post'
      Post.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("user_name LIKE ?", "#{value}%")
    elsif model == 'post'
      Post.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("user_name LIKE ?", "%#{value}")
    elsif model == 'post'
      Post.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("user_name LIKE ?", "%#{value}%")
    elsif model == 'post'
      Post.where("title LIKE ?", "%#{value}%")
    end
  end

  # ↓searchアクションで定義した情報が引数に入る
  # 検索方法の引数に(model, value)を定義
  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    root_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/users/blogs/index.html.erb
<div class="container col-9 mt-4 mb-5">
  <div>
    <h2 class="col text-center">管理人ブログ</h2>
    <%# 検索フォーム %>
  </div>
  <% @blogs.each do |blog| %>
  <div class="my-3 col-8 offset-2 text-center">
    <%= link_to blog_path(blog) do %>
    <div>
      <% if blog.blog_image.attached? %>
        <%= image_tag blog.blog_image.variant(resize: '534x330') %>
      <% end %>
    </div>
    <% end %>
    <div class="utable mx-4 mt-3 mb-5">
      <%= link_to blog_path(blog) do %>
        <h4><%= blog.title %></h4><br>
      <% end %>
      評価
      <div class="content d-flex justify-content-center">
        <div class="content average-score">
          <div class="star-rating mb-2">
            <div class="star-rating-front" style="width: <%= (blog.avg_score/5)*100 %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div>
        </div>
      </div>
      <%= blog.avg_score %>点（<%= blog.blog_comments.count %>件のレビュー）<br>
      コメント数：<%= blog.blog_comments.count %><br>
      <br>
      作成日：<%= blog.created_at.strftime('%Y/%m/%d %H:%M') %>&emsp;
      更新日：<%= blog.updated_at.strftime('%Y/%m/%d %H:%M') %>
    </div>
    <div class="col text-center">
      <%= paginate @blogs %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/blogs/show.html.erb
<div class="container col-9 mt-4 mb-5">
  <h2 class="col text-center"><%= @blog.title %></h2>
  <div class="my-3 col-8 offset-2 text-center">
    <div>
      <%= image_tag @blog.blog_image %>
    </div>
    <div class="utable my-4 mx-4">
      <h4 class="mb-4"><%= @blog.text %></h4><br>
      作成日：<%= @blog.created_at.strftime('%Y/%m/%d %H:%M') %>&emsp;
      更新日：<%= @blog.updated_at.strftime('%Y/%m/%d %H:%M') %>
    </div>
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-5">
            <div class="card mb-6">
              <header class="card-header">
                評価
              </header>
              <div class="card-content">
                <div class="content">
                  <div class="content average-score">
                    <div class="star-rating mb-2">
                      <div class="star-rating-front" style="width: <%= (@blog.avg_score/5)*100 %>%;">★★★★★</div>
                      <div class="star-rating-back">★★★★★</div>
                    </div>
                    <div class="average-score-display ml-3 pt-2">
                      <%= @blog.avg_score %>点（<%= @blog.blog_comments.count %>件のレビュー）
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @blog_comment.errors.any? %>
        <div class="notification is-danger">
          <h2><%= @blog_comment.errors.count %>件のエラーがあります。</h2>
          <ul>
            <% @blog_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <div>
        <%= form_with model:[@blog, @blog_comment], local: true do |f| %>
          <h5><p class="mt-5"><%= f.label :comment, "評価・コメント投稿" %></h5>
          <div class="rating-box mt-3 mb-4">
            <div class="main-rating">
              <div class="ratings mb-3">
                <span class="fa fa-star-o" id="star"></span>
                <span class="fa fa-star-o" id="star"></span>
                <span class="fa fa-star-o" id="star"></span>
                <span class="fa fa-star-o" id="star"></span>
                <span class="fa fa-star-o" id="star"></span>
              </div>
              <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
            </div>
            <%= f.hidden_field :blog_id, value: @blog.id %>
            <%= f.hidden_field :evaluation, id: "rating-value" %>
          </div>
          <%= f.text_area :comment, size: "60x5" , :placeholder => "コメントを入力" %><br>
          <div class="my-4">
            <%= f.submit "投稿", class: "btn btn-outline-success" %>
          </div>
        <% end %>
        </div>
      <% end %>
    <div class="mb-5 mx-4">
      <%= render "users/blog_comments/blog_comments", blog: @blog, blog_comment: @blog_comment %>
    </div>
    <div class="my-5">
      <%= link_to "管理人ブログ一覧", blogs_path, class: "mx-3 btn btn-outline-primary" %>&emsp;&emsp;
      <%= link_to "評価一覧", blog_blog_comments_path(@blog.id), class: "mx-3 btn btn-outline-success" %>
    </div>
  </div>
</div>


<%= javascript_include_tag "users/blog_comments.js" %>